At/devops/working solution
djangoheads/terraform-kubernetes-django pull request #1
Opened 2023-11-24 11:42 UTC by liquidbean

2023-11-24 12:35 UTC, sergio-bershadsky requested changes

2023-11-24 12:35 UTC, sergio-bershadsky commented on cloudflare.tf
> +resource "aws_acm_certificate" "main-cert" {
This chould be presented on upper level. And module must return everything needed for CloudFlare in outputs

2023-11-24 12:35 UTC, sergio-bershadsky commented on examples/solution/backend.tf
> +    dynamodb_table              = "terraform-lock-solution"
This should be presented in variables

2023-11-24 12:35 UTC, sergio-bershadsky commented on examples/solution/locals.tf
> +  namespace = "dev"
Should be presented in variable

2023-11-24 12:35 UTC, sergio-bershadsky commented on examples/solution/providers.tf
> +    role_arn    = "arn:aws:iam::387673871354:role/OrganizationAccountAccessRole"
This chould not be here

2023-11-24 12:35 UTC, sergio-bershadsky commented on examples/solution/providers.tf
> +  region                      = "eu-central-1"
This should not be here

2023-11-24 12:35 UTC, sergio-bershadsky commented on locals.tf
> +    Environment = "development"
This should not be here

2023-11-24 12:35 UTC, sergio-bershadsky commented on service.tf
>        target_port = 8000
Should be passed via variable

2023-11-24 12:38 UTC, HupBaHa approved these changes

2023-11-28 13:54 UTC, liquidbean commented on examples/solution/backend.tf
> +    dynamodb_table              = "terraform-lock-solution"
Cannot insert variables in the backend module

2023-11-28 13:59 UTC, liquidbean commented on cloudflare.tf
> +resource "aws_acm_certificate" "main-cert" {
Do I need to cut the cloudflare module completely from the solution?

2023-11-28 14:00 UTC, liquidbean commented on locals.tf
> +    Environment = "development"
where should I move this?

2023-12-07 08:25 UTC, sergio-bershadsky approved these changes

2023-12-07 08:26 UTC, merged